### ISSUE TITLE
just an aside question

### ISSUE THREAD

**Issue by ORESoftware** [cjihrig/helper.js#1]
I have been wondering this for as long as I have worked with JS

in your helper.js file, you pass in window to the self-invoking function like so:

``` js
(function foo(w){

})(window);
```

why not just reference window directly in the function?

``` js
(function foo(){
 window.bar = 'baz';
})();
```

never understood that I must say! There must be a reason, just curious, thanks

**Comment by cjihrig** [comment]
See https://toddmotto.com/what-function-window-document-undefined-iife-really-means/
